Dashboard/Controllers/DashboardController.cs
using Dashboard.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Dashboard.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ILogger<DashboardController> _logger;

        public DashboardController(ILogger<DashboardController> logger)
        {
            _logger = logger;
        }

        [Route("Team/{ip?}")]
        public IActionResult Team(long? ip)
        {
            TeamViewModel viewData = SqliteDataAccess.GetHistoryData(ip, SqliteDataAccess.LabelType.Ip) as TeamViewModel;
            return View(viewData);
        }

        [HttpGet]
        [Route("")]
        [Route("Results/{devArea?}/{group?}/{ip?}/{view?}")]
        public IActionResult Results(long? devArea, long? group, long? ip, long? view)
        {
            ResultViewModel viewData = SqliteDataAccess.GetResultsData(devArea, group, ip, view);
            return View(viewData);
        }

        [Route("Build/{group?}")]
        public IActionResult Build(long? group)
        {
            HistoryViewModel viewData = SqliteDataAccess.GetHistoryData(group, SqliteDataAccess.LabelType.Group);
            return View(viewData);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/lib/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/lib/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body id="page-top">

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/lib/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/lib/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/lib/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/lib/js/demo/datatables-demo.js"></script>

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <div class="sidebar-brand d-flex align-items-center justify-content-center">
                <div class="sidebar-brand-text mx-3">Dashboard</div>
            </div>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Dashboard" asp-action="Results">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Test Results</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>History</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Dashboard" asp-action="Team">Teams</a>
                        <a class="collapse-item" asp-controller="Dashboard" asp-action="Build">Builds</a>
                    </div>
                </div>
            </li>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
</body>
</html>